### PR TITLE
Clean up some wordiness

### PR DESCRIPTION
**Pull request by theovoss**
The gem looks pretty cool. Here's a few wording updates for your readme if you want them. I could easily understand the purpose and how to use this gem. this should just clean up some wordiness.

### CODE REVIEW

**Comment by ka8725** [comment]
Great! Thanks, @theovoss !

**Comment by theovoss** [comment]
:+1: no problem @ka8725 any other readme's you want me to do a quick look-over?

**Comment by ka8725** [comment]
I just have 2 more useful gems: https://github.com/mezuka/static_struct and https://github.com/mezuka/enum

If you are interesting in this - you are welcome. Thanks in advance!

**Comment by theovoss** [comment]
The logic behind these gems is pretty straightforward, but the Readme's for
them could both use more work than the readme for migration_data (and more
than I'm willing to do immediately). If you don't get PR's for those gems
in about a week hit me up and remind me. I'll try to get to them within a
day or two, but sometimes I forget about things.

**Pull request merged**
